
(function(){
  const read=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
  const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  const user=()=>read('cf_currentUser',null);
  const appointments=()=>read('cf_appointments',[]);
  const records=()=>read('cf_patientRecords',[]);
  const recordKey=(u)=>String(u.email||'').toLowerCase();
  const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  function safeText(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function requirePatient(){const u=user();if(!u||u.role!=='user'){location.href='login.html';return null}return u;}
  function initRecords(){
    const form=document.getElementById('recordForm');if(!form)return;const u=requirePatient();if(!u)return;
    const list=document.getElementById('recordList'),count=document.getElementById('recordCount'),msg=document.getElementById('recordMsg'),date=document.getElementById('recordDate');if(date&&!date.value)date.value=todayISO();
    function render(){const items=records().filter(r=>r.owner===recordKey(u)).sort((a,b)=>b.date.localeCompare(a.date));count.textContent=`${items.length} record${items.length===1?'':'s'}`;list.innerHTML=items.length?items.map(r=>`<article class="record-card"><div class="record-card-top"><span class="record-type">${safeText(r.type)}</span><time>${safeText(r.date)}</time></div><h3>${safeText(r.title)}</h3><p>${safeText(r.notes)}</p><div class="record-actions"><button class="btn-small" data-edit-record="${r.id}">Edit</button><button class="btn-small btn-danger" data-delete-record="${r.id}">Delete</button></div></article>`).join(''):'<div class="empty">No notes saved yet. Add a personal record using the form.</div>';
      list.querySelectorAll('[data-edit-record]').forEach(b=>b.addEventListener('click',()=>{const r=records().find(x=>x.id===Number(b.dataset.editRecord)&&x.owner===recordKey(u));if(!r)return;document.getElementById('recordId').value=r.id;document.getElementById('recordTitle').value=r.title;document.getElementById('recordType').value=r.type;document.getElementById('recordDate').value=r.date;document.getElementById('recordNotes').value=r.notes;document.getElementById('recordFormTitle').textContent='Edit personal record';document.getElementById('cancelRecordEdit').classList.remove('hidden');form.scrollIntoView({behavior:'smooth',block:'start'});}));
      list.querySelectorAll('[data-delete-record]').forEach(b=>b.addEventListener('click',()=>{if(!confirm('Delete this record?'))return;write('cf_patientRecords',records().filter(x=>!(x.id===Number(b.dataset.deleteRecord)&&x.owner===recordKey(u))));render();}));
    }
    function reset(){form.reset();document.getElementById('recordId').value='';document.getElementById('recordFormTitle').textContent='Add a personal record';document.getElementById('cancelRecordEdit').classList.add('hidden');date.value=todayISO();}
    form.addEventListener('submit',e=>{e.preventDefault();const all=records(),id=document.getElementById('recordId').value;const item={id:id?Number(id):Date.now(),owner:recordKey(u),patientName:u.name,title:document.getElementById('recordTitle').value.trim(),type:document.getElementById('recordType').value,date:date.value,notes:document.getElementById('recordNotes').value.trim()};if(!item.title||!item.notes)return;const idx=all.findIndex(x=>x.id===item.id&&x.owner===item.owner);if(idx>=0)all[idx]=item;else all.push(item);write('cf_patientRecords',all);msg.textContent='Record saved successfully.';msg.style.color='#16805d';reset();render();});
    document.getElementById('cancelRecordEdit').addEventListener('click',reset);render();
  }
  function initVirtualVisits(){
    const list=document.getElementById('virtualAppointmentList');if(!list)return;const u=requirePatient();if(!u)return;
    const room=document.getElementById('virtualRoom');let mic=false,camera=false;
    const items=appointments().filter(a=>a.userEmail===u.email&&String(a.visitMode||'').toLowerCase().includes('video')&&a.status!=='Cancelled').sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));
    list.innerHTML=items.length?items.map(a=>`<article class="virtual-card"><div class="virtual-card-icon">◉</div><div class="virtual-card-main"><h3>${safeText(a.doctorName)}</h3><p>${safeText(a.specialization)} · ${safeText(a.date)} · ${safeText(a.time)}</p><span class="pill ${a.status==='Completed'?'':'success'}">${safeText(a.status)}</span></div><button class="btn btn-primary" data-join-visit="${a.id}" ${a.status==='Completed'?'disabled':''}>Open demo room →</button></article>`).join(''):'<div class="empty">No video consultations found. When booking, choose “Video consultation” for a doctor who offers it.</div>';
    list.querySelectorAll('[data-join-visit]').forEach(b=>b.addEventListener('click',()=>{const a=items.find(x=>x.id===Number(b.dataset.joinVisit));if(!a)return;document.getElementById('roomDoctorName').textContent=a.doctorName;document.getElementById('roomAppointmentMeta').textContent=`${a.specialization} · ${a.date} · ${a.time}`;room.classList.remove('hidden');room.scrollIntoView({behavior:'smooth',block:'start'});}));
    const micBtn=document.getElementById('toggleMic'),camBtn=document.getElementById('toggleCamera');micBtn.addEventListener('click',()=>{mic=!mic;micBtn.textContent=`🎙 Microphone: ${mic?'On (simulated)':'Off'}`;});camBtn.addEventListener('click',()=>{camera=!camera;camBtn.textContent=`▣ Camera: ${camera?'On (simulated)':'Off'}`;});
    const leave=()=>{room.classList.add('hidden');mic=false;camera=false;micBtn.textContent='🎙 Microphone: Off';camBtn.textContent='▣ Camera: Off';};document.getElementById('leaveRoom').addEventListener('click',leave);document.getElementById('endConsultation').addEventListener('click',leave);
  }
  function initScheduleInsights(){
    const root=document.getElementById('scheduleInsights');if(!root)return;const all=appointments().filter(a=>a.status!=='Cancelled');const docs=read('cf_doctors',[]);const users=read('cf_users',[]);const byDoctor={};const byDate={};all.forEach(a=>{byDoctor[a.doctorName]=(byDoctor[a.doctorName]||0)+1;byDate[a.date]=(byDate[a.date]||0)+1});const busiestDoctor=Object.entries(byDoctor).sort((a,b)=>b[1]-a[1])[0];const busiestDay=Object.entries(byDate).sort((a,b)=>b[1]-a[1])[0];const avg=all.length?Math.round(all.reduce((n,a)=>n+(Number(a.estimatedWait)||0),0)/all.length):0;const cards=[['Confirmed / active visits',all.length,'Based on non-cancelled demo bookings'],['Doctors listed',docs.length,'Available profiles in the directory'],['Busiest doctor',busiestDoctor?busiestDoctor[0]:'No bookings yet',busiestDoctor?`${busiestDoctor[1]} appointment(s)`:'New bookings will appear here'],['Busiest date',busiestDay?busiestDay[0]:'No bookings yet',busiestDay?`${busiestDay[1]} appointment(s)`:'No schedule data yet'],['Estimated average wait',`${avg} min`,'Illustrative estimate based on earlier slots'],['Registered patients',users.length,'Local demo accounts']];root.innerHTML=cards.map(c=>`<article class="insight-card"><span>${safeText(c[0])}</span><strong>${safeText(c[1])}</strong><small>${safeText(c[2])}</small></article>`).join('');
    const table=document.getElementById('adminRecordsTable');if(table){const allRecords=records();table.innerHTML=allRecords.length?`<table class="table"><thead><tr><th>Patient</th><th>Record</th><th>Type</th><th>Date</th><th>Note preview</th></tr></thead><tbody>${allRecords.map(r=>`<tr><td>${safeText(r.patientName)}</td><td>${safeText(r.title)}</td><td>${safeText(r.type)}</td><td>${safeText(r.date)}</td><td>${safeText(r.notes.slice(0,70))}${r.notes.length>70?'…':''}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No patient records have been added in this browser demo.</div>';}
  }
  function addReminderPanel(){
    const target=document.getElementById('reminderText');if(!target)return;const u=requirePatient();if(!u)return;const list=appointments().filter(a=>a.userEmail===u.email&&a.status==='Confirmed').sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));const today=todayISO();const upcoming=list.filter(a=>a.date>=today);if(!upcoming.length){target.textContent='No upcoming appointment yet.';return;}const next=upcoming[0];const days=Math.round((new Date(next.date+'T00:00:00')-new Date(today+'T00:00:00'))/86400000);const when=days===0?'today':days===1?'tomorrow':`in ${days} days`;target.textContent=`Reminder: your appointment with ${next.doctorName} is ${when} (${next.date}) at ${next.time}. ${next.visitMode==='Video consultation'?'Open Virtual Visits before your consultation.':'Plan your travel and arrive a little early.'}`;
  }
  document.addEventListener('DOMContentLoaded',()=>{initRecords();initVirtualVisits();initScheduleInsights();addReminderPanel();});
})();
